from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation, QTimer, QParallelAnimationGroup


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1248, 777)
        self.Output = QtWidgets.QTextEdit(Form)
        self.Output.setGeometry(QtCore.QRect(1090, 10, 270, 671))
        self.Output.setObjectName("Output")
        self.Output.setReadOnly(1)
        self.Output.setFontPointSize(12)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 541, 681))
        self.widget.setObjectName("widget")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setPixmap(QtGui.QPixmap("Images/gym_mod1.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_21 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.U19 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U19.sizePolicy().hasHeightForWidth())
        self.U19.setSizePolicy(sizePolicy)
        self.U19.setMinimumSize(QtCore.QSize(50, 29))
        self.U19.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.U19.setIcon(icon)
        self.U19.setIconSize(QtCore.QSize(20, 19))
        self.U19.setObjectName("U19")
        self.U19.setEnabled(False)
        # self.U19.clicked.connect(lambda: self.startAnimation(self.U19))
        self.horizontalLayout.addWidget(self.U19)
        self.D19 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D19.sizePolicy().hasHeightForWidth())
        self.D19.setSizePolicy(sizePolicy)
        self.D19.setMinimumSize(QtCore.QSize(50, 29))
        self.D19.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.D19.setIcon(icon1)
        self.D19.setIconSize(QtCore.QSize(20, 19))
        self.D19.setObjectName("D19")
        self.D19.clicked.connect(lambda: self.startAnimation(self.D19))
        self.horizontalLayout.addWidget(self.D19)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_22 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.U18 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U18.sizePolicy().hasHeightForWidth())
        self.U18.setSizePolicy(sizePolicy)
        self.U18.setMinimumSize(QtCore.QSize(50, 29))
        self.U18.setText("")
        self.U18.setIcon(icon)
        self.U18.setIconSize(QtCore.QSize(20, 19))
        self.U18.setObjectName("U18")
        self.U18.clicked.connect(lambda: self.startAnimation(self.U18))
        self.horizontalLayout_2.addWidget(self.U18)
        self.D18 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D18.sizePolicy().hasHeightForWidth())
        self.D18.setSizePolicy(sizePolicy)
        self.D18.setMinimumSize(QtCore.QSize(50, 29))
        self.D18.setText("")
        self.D18.setIcon(icon1)
        self.D18.setIconSize(QtCore.QSize(20, 19))
        self.D18.setObjectName("D18")
        self.D18.clicked.connect(lambda: self.startAnimation(self.D18))
        self.horizontalLayout_2.addWidget(self.D18)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(40, 0))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_23 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.U17 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U17.sizePolicy().hasHeightForWidth())
        self.U17.setSizePolicy(sizePolicy)
        self.U17.setMinimumSize(QtCore.QSize(50, 29))
        self.U17.setText("")
        self.U17.setIcon(icon)
        self.U17.setIconSize(QtCore.QSize(20, 19))
        self.U17.setObjectName("U17")
        self.U17.clicked.connect(lambda: self.startAnimation(self.U17))
        self.horizontalLayout_3.addWidget(self.U17)
        self.D17 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D17.sizePolicy().hasHeightForWidth())
        self.D17.setSizePolicy(sizePolicy)
        self.D17.setMinimumSize(QtCore.QSize(50, 29))
        self.D17.setText("")
        self.D17.setIcon(icon1)
        self.D17.setIconSize(QtCore.QSize(20, 19))
        self.D17.setObjectName("D17")
        self.D17.clicked.connect(lambda: self.startAnimation(self.D17))
        self.horizontalLayout_3.addWidget(self.D17)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_24 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.U16 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U16.sizePolicy().hasHeightForWidth())
        self.U16.setSizePolicy(sizePolicy)
        self.U16.setMinimumSize(QtCore.QSize(50, 29))
        self.U16.setText("")
        self.U16.setIcon(icon)
        self.U16.setIconSize(QtCore.QSize(20, 19))
        self.U16.setObjectName("U16")
        self.U16.clicked.connect(lambda: self.startAnimation(self.U16))
        self.horizontalLayout_4.addWidget(self.U16)
        self.D16 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D16.sizePolicy().hasHeightForWidth())
        self.D16.setSizePolicy(sizePolicy)
        self.D16.setMinimumSize(QtCore.QSize(50, 29))
        self.D16.setText("")
        self.D16.setIcon(icon1)
        self.D16.setIconSize(QtCore.QSize(20, 19))
        self.D16.setObjectName("D16")
        self.D16.clicked.connect(lambda: self.startAnimation(self.D16))
        self.horizontalLayout_4.addWidget(self.D16)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(40, 0))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_25 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.U15 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U15.sizePolicy().hasHeightForWidth())
        self.U15.setSizePolicy(sizePolicy)
        self.U15.setMinimumSize(QtCore.QSize(50, 29))
        self.U15.setText("")
        self.U15.setIcon(icon)
        self.U15.setIconSize(QtCore.QSize(20, 19))
        self.U15.setObjectName("U15")
        self.U15.clicked.connect(lambda: self.startAnimation(self.U15))
        self.horizontalLayout_5.addWidget(self.U15)
        self.D15 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D15.sizePolicy().hasHeightForWidth())
        self.D15.setSizePolicy(sizePolicy)
        self.D15.setMinimumSize(QtCore.QSize(50, 29))
        self.D15.setText("")
        self.D15.setIcon(icon1)
        self.D15.setIconSize(QtCore.QSize(20, 19))
        self.D15.setObjectName("D15")
        self.D15.clicked.connect(lambda: self.startAnimation(self.D15))
        self.horizontalLayout_5.addWidget(self.D15)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(40, 0))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_226 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_226.setFont(font)
        self.label_226.setObjectName("label_226")
        self.horizontalLayout_6.addWidget(self.label_226)
        self.U14 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U14.sizePolicy().hasHeightForWidth())
        self.U14.setSizePolicy(sizePolicy)
        self.U14.setMinimumSize(QtCore.QSize(50, 29))
        self.U14.setText("")
        self.U14.setIcon(icon)
        self.U14.setIconSize(QtCore.QSize(20, 19))
        self.U14.setObjectName("U14")
        self.U14.clicked.connect(lambda: self.startAnimation(self.U14))
        self.horizontalLayout_6.addWidget(self.U14)
        self.D14 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D14.sizePolicy().hasHeightForWidth())
        self.D14.setSizePolicy(sizePolicy)
        self.D14.setMinimumSize(QtCore.QSize(50, 29))
        self.D14.setText("")
        self.D14.setIcon(icon1)
        self.D14.setIconSize(QtCore.QSize(20, 19))
        self.D14.setObjectName("D14")
        self.D14.clicked.connect(lambda: self.startAnimation(self.D14))
        self.horizontalLayout_6.addWidget(self.D14)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(40, 0))
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setLineWidth(1)
        self.label_7.setMidLineWidth(0)
        self.label_7.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_227 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_227.setFont(font)
        self.label_227.setObjectName("label_227")
        self.horizontalLayout_7.addWidget(self.label_227)
        self.U13 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U13.sizePolicy().hasHeightForWidth())
        self.U13.setSizePolicy(sizePolicy)
        self.U13.setMinimumSize(QtCore.QSize(50, 29))
        self.U13.setText("")
        self.U13.setIcon(icon)
        self.U13.setIconSize(QtCore.QSize(20, 19))
        self.U13.setObjectName("U13")
        self.U13.clicked.connect(lambda: self.startAnimation(self.U13))
        self.horizontalLayout_7.addWidget(self.U13)
        self.D13 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D13.sizePolicy().hasHeightForWidth())
        self.D13.setSizePolicy(sizePolicy)
        self.D13.setMinimumSize(QtCore.QSize(50, 29))
        self.D13.setText("")
        self.D13.setIcon(icon1)
        self.D13.setIconSize(QtCore.QSize(20, 19))
        self.D13.setObjectName("D13")
        self.D13.clicked.connect(lambda: self.startAnimation(self.D13))
        self.horizontalLayout_7.addWidget(self.D13)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(40, 0))
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setLineWidth(1)
        self.label_8.setMidLineWidth(0)
        self.label_8.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_228 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_228.setFont(font)
        self.label_228.setObjectName("label_228")
        self.horizontalLayout_8.addWidget(self.label_228)
        self.U12 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U12.sizePolicy().hasHeightForWidth())
        self.U12.setSizePolicy(sizePolicy)
        self.U12.setMinimumSize(QtCore.QSize(50, 29))
        self.U12.setText("")
        self.U12.setIcon(icon)
        self.U12.setIconSize(QtCore.QSize(20, 19))
        self.U12.setObjectName("U12")
        self.U12.clicked.connect(lambda: self.startAnimation(self.U12))
        self.horizontalLayout_8.addWidget(self.U12)
        self.D12 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D12.sizePolicy().hasHeightForWidth())
        self.D12.setSizePolicy(sizePolicy)
        self.D12.setMinimumSize(QtCore.QSize(50, 29))
        self.D12.setText("")
        self.D12.setIcon(icon1)
        self.D12.setIconSize(QtCore.QSize(20, 19))
        self.D12.setObjectName("D12")
        self.D12.clicked.connect(lambda: self.startAnimation(self.D12))
        self.horizontalLayout_8.addWidget(self.D12)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(40, 0))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setPixmap(QtGui.QPixmap("Images/sm_mod1.jpg"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.label_229 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_229.setFont(font)
        self.label_229.setObjectName("label_229")
        self.horizontalLayout_9.addWidget(self.label_229)
        self.U11 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U11.sizePolicy().hasHeightForWidth())
        self.U11.setSizePolicy(sizePolicy)
        self.U11.setMinimumSize(QtCore.QSize(50, 29))
        self.U11.setText("")
        self.U11.setIcon(icon)
        self.U11.setIconSize(QtCore.QSize(20, 19))
        self.U11.setObjectName("U11")
        self.U11.clicked.connect(lambda: self.startAnimation(self.U11))
        self.horizontalLayout_9.addWidget(self.U11)
        self.D11 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D11.sizePolicy().hasHeightForWidth())
        self.D11.setSizePolicy(sizePolicy)
        self.D11.setMinimumSize(QtCore.QSize(50, 29))
        self.D11.setText("")
        self.D11.setIcon(icon1)
        self.D11.setIconSize(QtCore.QSize(20, 19))
        self.D11.setObjectName("D11")
        self.D11.clicked.connect(lambda: self.startAnimation(self.D11))
        self.horizontalLayout_9.addWidget(self.D11)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 0))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setLineWidth(1)
        self.label_10.setMidLineWidth(0)
        self.label_10.setPixmap(QtGui.QPixmap("Images/sm_mod1.jpg"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_30 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.U10 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U10.sizePolicy().hasHeightForWidth())
        self.U10.setSizePolicy(sizePolicy)
        self.U10.setMinimumSize(QtCore.QSize(50, 29))
        self.U10.setText("")
        self.U10.setIcon(icon)
        self.U10.setIconSize(QtCore.QSize(20, 19))
        self.U10.setObjectName("U10")
        self.U10.clicked.connect(lambda: self.startAnimation(self.U10))
        self.horizontalLayout_10.addWidget(self.U10)
        self.D10 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D10.sizePolicy().hasHeightForWidth())
        self.D10.setSizePolicy(sizePolicy)
        self.D10.setMinimumSize(QtCore.QSize(50, 29))
        self.D10.setText("")
        self.D10.setIcon(icon1)
        self.D10.setIconSize(QtCore.QSize(20, 19))
        self.D10.setObjectName("D10")
        self.D10.clicked.connect(lambda: self.startAnimation(self.D10))
        self.horizontalLayout_10.addWidget(self.D10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setLineWidth(1)
        self.label_11.setMidLineWidth(0)
        self.label_11.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.label_31 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_11.addWidget(self.label_31)
        self.U9 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U9.sizePolicy().hasHeightForWidth())
        self.U9.setSizePolicy(sizePolicy)
        self.U9.setMinimumSize(QtCore.QSize(50, 29))
        self.U9.setText("")
        self.U9.setIcon(icon)
        self.U9.setIconSize(QtCore.QSize(20, 19))
        self.U9.setObjectName("U9")
        self.U9.clicked.connect(lambda: self.startAnimation(self.U9))
        self.horizontalLayout_11.addWidget(self.U9)
        self.D9 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D9.sizePolicy().hasHeightForWidth())
        self.D9.setSizePolicy(sizePolicy)
        self.D9.setMinimumSize(QtCore.QSize(50, 29))
        self.D9.setText("")
        self.D9.setIcon(icon1)
        self.D9.setIconSize(QtCore.QSize(20, 19))
        self.D9.setObjectName("D9")
        self.D9.clicked.connect(lambda: self.startAnimation(self.D9))
        self.horizontalLayout_11.addWidget(self.D9)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(40, 0))
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setLineWidth(1)
        self.label_12.setMidLineWidth(0)
        self.label_12.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.label_32 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_12.addWidget(self.label_32)
        self.U8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U8.sizePolicy().hasHeightForWidth())
        self.U8.setSizePolicy(sizePolicy)
        self.U8.setMinimumSize(QtCore.QSize(50, 29))
        self.U8.setText("")
        self.U8.setIcon(icon)
        self.U8.setIconSize(QtCore.QSize(20, 19))
        self.U8.setObjectName("U8")
        self.U8.clicked.connect(lambda: self.startAnimation(self.U8))
        self.horizontalLayout_12.addWidget(self.U8)
        self.D8 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D8.sizePolicy().hasHeightForWidth())
        self.D8.setSizePolicy(sizePolicy)
        self.D8.setMinimumSize(QtCore.QSize(50, 29))
        self.D8.setText("")
        self.D8.setIcon(icon1)
        self.D8.setIconSize(QtCore.QSize(20, 19))
        self.D8.setObjectName("D8")
        self.D8.clicked.connect(lambda: self.startAnimation(self.D8))
        self.horizontalLayout_12.addWidget(self.D8)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(40, 0))
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setLineWidth(1)
        self.label_13.setMidLineWidth(0)
        self.label_13.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.label_33 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_13.addWidget(self.label_33)
        self.U7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U7.sizePolicy().hasHeightForWidth())
        self.U7.setSizePolicy(sizePolicy)
        self.U7.setMinimumSize(QtCore.QSize(50, 29))
        self.U7.setText("")
        self.U7.setIcon(icon)
        self.U7.setIconSize(QtCore.QSize(20, 19))
        self.U7.setObjectName("U7")
        self.U7.clicked.connect(lambda: self.startAnimation(self.U7))
        self.horizontalLayout_13.addWidget(self.U7)
        self.D7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        self.D7.setMinimumSize(QtCore.QSize(50, 29))
        self.D7.setText("")
        self.D7.setIcon(icon1)
        self.D7.setIconSize(QtCore.QSize(20, 19))
        self.D7.setObjectName("D7")
        self.D7.clicked.connect(lambda: self.startAnimation(self.D7))
        self.horizontalLayout_13.addWidget(self.D7)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(40, 0))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setLineWidth(1)
        self.label_14.setMidLineWidth(0)
        self.label_14.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.label_34 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_14.addWidget(self.label_34)
        self.U6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U6.sizePolicy().hasHeightForWidth())
        self.U6.setSizePolicy(sizePolicy)
        self.U6.setMinimumSize(QtCore.QSize(50, 29))
        self.U6.setText("")
        self.U6.setIcon(icon)
        self.U6.setIconSize(QtCore.QSize(20, 19))
        self.U6.setObjectName("U6")
        self.U6.clicked.connect(lambda: self.startAnimation(self.U6))
        self.horizontalLayout_14.addWidget(self.U6)
        self.D6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6.sizePolicy().hasHeightForWidth())
        self.D6.setSizePolicy(sizePolicy)
        self.D6.setMinimumSize(QtCore.QSize(50, 29))
        self.D6.setText("")
        self.D6.setIcon(icon1)
        self.D6.setIconSize(QtCore.QSize(20, 19))
        self.D6.setObjectName("D6")
        self.D6.clicked.connect(lambda: self.startAnimation(self.D6))
        self.horizontalLayout_14.addWidget(self.D6)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(40, 0))
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(0)
        self.label_15.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.label_35 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_15.addWidget(self.label_35)
        self.U5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U5.sizePolicy().hasHeightForWidth())
        self.U5.setSizePolicy(sizePolicy)
        self.U5.setMinimumSize(QtCore.QSize(50, 29))
        self.U5.setText("")
        self.U5.setIcon(icon)
        self.U5.setIconSize(QtCore.QSize(20, 19))
        self.U5.setObjectName("U5")
        self.U5.clicked.connect(lambda: self.startAnimation(self.U5))
        self.horizontalLayout_15.addWidget(self.U5)
        self.D5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        self.D5.setMinimumSize(QtCore.QSize(50, 29))
        self.D5.setText("")
        self.D5.setIcon(icon1)
        self.D5.setIconSize(QtCore.QSize(20, 19))
        self.D5.setObjectName("D5")
        self.D5.clicked.connect(lambda: self.startAnimation(self.D5))
        self.horizontalLayout_15.addWidget(self.D5)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(40, 0))
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setLineWidth(1)
        self.label_16.setMidLineWidth(0)
        self.label_16.setPixmap(QtGui.QPixmap("Images/office_mod1.jpg"))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.label_36 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_16.addWidget(self.label_36)
        self.U4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U4.sizePolicy().hasHeightForWidth())
        self.U4.setSizePolicy(sizePolicy)
        self.U4.setMinimumSize(QtCore.QSize(50, 29))
        self.U4.setText("")
        self.U4.setIcon(icon)
        self.U4.setIconSize(QtCore.QSize(20, 19))
        self.U4.setObjectName("U4")
        self.U4.clicked.connect(lambda: self.startAnimation(self.U4))
        self.horizontalLayout_16.addWidget(self.U4)
        self.D4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4.sizePolicy().hasHeightForWidth())
        self.D4.setSizePolicy(sizePolicy)
        self.D4.setMinimumSize(QtCore.QSize(50, 29))
        self.D4.setText("")
        self.D4.setIcon(icon1)
        self.D4.setIconSize(QtCore.QSize(20, 19))
        self.D4.setObjectName("D4")
        self.D4.clicked.connect(lambda: self.startAnimation(self.D4))
        self.horizontalLayout_16.addWidget(self.D4)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(40, 0))
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setLineWidth(1)
        self.label_17.setMidLineWidth(0)
        self.label_17.setPixmap(QtGui.QPixmap("Images/library_mod1.jpg"))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.label_37 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_17.addWidget(self.label_37)
        self.U3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U3.sizePolicy().hasHeightForWidth())
        self.U3.setSizePolicy(sizePolicy)
        self.U3.setMinimumSize(QtCore.QSize(50, 29))
        self.U3.setText("")
        self.U3.setIcon(icon)
        self.U3.setIconSize(QtCore.QSize(20, 19))
        self.U3.setObjectName("U3")
        self.U3.clicked.connect(lambda: self.startAnimation(self.U3))
        self.horizontalLayout_17.addWidget(self.U3)
        self.D3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        self.D3.setMinimumSize(QtCore.QSize(50, 29))
        self.D3.setText("")
        self.D3.setIcon(icon1)
        self.D3.setIconSize(QtCore.QSize(20, 19))
        self.D3.setObjectName("D3")
        self.D3.clicked.connect(lambda: self.startAnimation(self.D3))
        self.horizontalLayout_17.addWidget(self.D3)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(40, 0))
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setLineWidth(1)
        self.label_18.setMidLineWidth(0)
        self.label_18.setPixmap(QtGui.QPixmap("Images/coaching_mod1.jpg"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.label_38 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_18.addWidget(self.label_38)
        self.U2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U2.sizePolicy().hasHeightForWidth())
        self.U2.setSizePolicy(sizePolicy)
        self.U2.setMinimumSize(QtCore.QSize(50, 29))
        self.U2.setText("")
        self.U2.setIcon(icon)
        self.U2.setIconSize(QtCore.QSize(20, 19))
        self.U2.setObjectName("U2")
        self.U2.clicked.connect(lambda: self.startAnimation(self.U2))
        self.horizontalLayout_18.addWidget(self.U2)
        self.D2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2.sizePolicy().hasHeightForWidth())
        self.D2.setSizePolicy(sizePolicy)
        self.D2.setMinimumSize(QtCore.QSize(50, 29))
        self.D2.setText("")
        self.D2.setIcon(icon1)
        self.D2.setIconSize(QtCore.QSize(20, 19))
        self.D2.setObjectName("D2")
        self.D2.clicked.connect(lambda: self.startAnimation(self.D2))
        self.horizontalLayout_18.addWidget(self.D2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(40, 0))
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setLineWidth(1)
        self.label_19.setMidLineWidth(0)
        self.label_19.setPixmap(QtGui.QPixmap("Images/coaching_mod1.jpg"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.label_39 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_19.addWidget(self.label_39)
        self.U1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.U1.sizePolicy().hasHeightForWidth())
        self.U1.setSizePolicy(sizePolicy)
        self.U1.setMinimumSize(QtCore.QSize(50, 29))
        self.U1.setText("")
        self.U1.setIcon(icon)
        self.U1.setIconSize(QtCore.QSize(20, 19))
        self.U1.setObjectName("U1")
        self.U1.clicked.connect(lambda: self.startAnimation(self.U1))
        self.horizontalLayout_19.addWidget(self.U1)
        self.D1 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1.sizePolicy().hasHeightForWidth())
        self.D1.setSizePolicy(sizePolicy)
        self.D1.setMinimumSize(QtCore.QSize(50, 29))
        self.D1.setText("")
        self.D1.setIcon(icon1)
        self.D1.setIconSize(QtCore.QSize(20, 19))
        self.D1.setObjectName("D1")
        self.D1.clicked.connect(lambda: self.startAnimation(self.D1))
        self.horizontalLayout_19.addWidget(self.D1)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(40, 0))
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setLineWidth(1)
        self.label_20.setMidLineWidth(0)
        self.label_20.setPixmap(QtGui.QPixmap("Images/bank_mod1.jpg"))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.label_40 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_20.addWidget(self.label_40)
        self.UG = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UG.sizePolicy().hasHeightForWidth())
        self.UG.setSizePolicy(sizePolicy)
        self.UG.setMinimumSize(QtCore.QSize(50, 29))
        self.UG.setText("")
        self.UG.setIcon(icon)
        self.UG.setIconSize(QtCore.QSize(20, 19))
        self.UG.setObjectName("U0")
        self.UG.clicked.connect(lambda: self.startAnimation(self.UG))
        self.horizontalLayout_20.addWidget(self.UG)
        self.DG = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DG.sizePolicy().hasHeightForWidth())
        self.DG.setSizePolicy(sizePolicy)
        self.DG.setMinimumSize(QtCore.QSize(50, 29))
        self.DG.setText("")
        self.DG.setIcon(icon1)
        self.DG.setIconSize(QtCore.QSize(20, 19))
        self.DG.setObjectName("DG")
        self.DG.setEnabled(False)
        # self.DG.clicked.connect(lambda: self.startAnimation(self.DG))
        self.horizontalLayout_20.addWidget(self.DG)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22.addLayout(self.verticalLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.Box1 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box1.sizePolicy().hasHeightForWidth())
        self.Box1.setSizePolicy(sizePolicy)
        self.Box1.setMinimumSize(QtCore.QSize(84, 678))
        self.Box1.setAutoFillBackground(False)
        self.Box1.setFrameShape(QtWidgets.QFrame.Box)
        self.Box1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Box1.setLineWidth(1)
        self.Box1.setObjectName("Box1")
        self.Car1 = QtWidgets.QLabel(self.Box1)
        self.Car1.setGeometry(QtCore.QRect(30, 650, 30, 28))
        self.Car1.setText("")
        self.Car1.setPixmap(QtGui.QPixmap("Images/close.jpg"))
        self.Car1.setAlignment(QtCore.Qt.AlignCenter)
        self.Car1.setObjectName("Car1")
        self.horizontalLayout_21.addWidget(self.Box1)
        self.Box2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box2.sizePolicy().hasHeightForWidth())
        self.Box2.setSizePolicy(sizePolicy)
        self.Box2.setMinimumSize(QtCore.QSize(84, 678))
        self.Box2.setAutoFillBackground(False)
        self.Box2.setFrameShape(QtWidgets.QFrame.Box)
        self.Box2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Box2.setLineWidth(1)
        self.Box2.setObjectName("Box2")
        self.Car2 = QtWidgets.QLabel(self.Box2)
        self.Car2.setGeometry(QtCore.QRect(30, 650, 30, 28))
        self.Car2.setText("")
        self.Car2.setAlignment(QtCore.Qt.AlignCenter)
        self.Car2.setPixmap(QtGui.QPixmap("Images/close.jpg"))
        self.Car2.setObjectName("Car2")
        self.horizontalLayout_21.addWidget(self.Box2)
        self.Box3 = QtWidgets.QFrame(self.widget)
        self.Box3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box3.sizePolicy().hasHeightForWidth())
        self.Box3.setSizePolicy(sizePolicy)
        self.Box3.setMinimumSize(QtCore.QSize(84, 678))
        self.Box3.setAutoFillBackground(False)
        self.Box3.setFrameShape(QtWidgets.QFrame.Box)
        self.Box3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Box3.setLineWidth(1)
        self.Box3.setObjectName("Box3")
        self.Car3 = QtWidgets.QLabel(self.Box3)
        self.Car3.setGeometry(QtCore.QRect(30, 650, 30, 28))
        self.Car3.setText("")
        self.Car3.setAlignment(QtCore.Qt.AlignCenter)
        self.Car3.setPixmap(QtGui.QPixmap("Images/close.jpg"))
        self.Car3.setObjectName("Car3")
        self.horizontalLayout_21.addWidget(self.Box3)
        self.Box4 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box4.sizePolicy().hasHeightForWidth())
        self.Box4.setSizePolicy(sizePolicy)
        self.Box4.setMinimumSize(QtCore.QSize(84, 678))
        self.Box4.setAutoFillBackground(False)
        self.Box4.setFrameShape(QtWidgets.QFrame.Box)
        self.Box4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Box4.setLineWidth(1)
        self.Box4.setObjectName("Box4")
        self.Car4 = QtWidgets.QLabel(self.Box4)
        self.Car4.setGeometry(QtCore.QRect(30, 650, 30, 28))
        self.Car4.setText("")
        self.Car4.setAlignment(QtCore.Qt.AlignCenter)
        self.Car4.setPixmap(QtGui.QPixmap("Images/close.jpg"))
        self.Car4.setObjectName("Car4")
        self.horizontalLayout_21.addWidget(self.Box4)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(560, 10, 521, 681))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_9 = QtWidgets.QFrame(self.widget1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.Queue3 = QtWidgets.QTextEdit(self.frame_9)
        self.Queue3.setGeometry(QtCore.QRect(10, 42, 231, 91))
        self.Queue3.setObjectName("Queue3")
        self.Queue3.setReadOnly(1)
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(16, 2, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.L3_Dest = QtWidgets.QFrame(self.frame_9)
        self.L3_Dest.setGeometry(QtCore.QRect(0, 140, 251, 211))
        self.L3_Dest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.L3_Dest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.L3_Dest.setObjectName("L3_Dest")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.L3_Dest)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.L3_16 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_16.setObjectName("L3_16")
        self.L3_16.clicked.connect(lambda: self.startAnimation(self.L3_16))
        self.gridLayout_7.addWidget(self.L3_16, 0, 0, 1, 1)
        self.L3_17 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_17.setObjectName("L3_17")
        self.L3_17.clicked.connect(lambda: self.startAnimation(self.L3_17))
        self.gridLayout_7.addWidget(self.L3_17, 0, 1, 1, 1)
        self.L3_18 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_18.setObjectName("L3_18")
        self.L3_18.clicked.connect(lambda: self.startAnimation(self.L3_18))
        self.gridLayout_7.addWidget(self.L3_18, 0, 2, 1, 1)
        self.L3_19 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_19.setObjectName("L3_19")
        self.L3_19.clicked.connect(lambda: self.startAnimation(self.L3_19))
        self.gridLayout_7.addWidget(self.L3_19, 0, 3, 1, 1)
        self.L3_12 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_12.setObjectName("L3_12")
        self.L3_12.clicked.connect(lambda: self.startAnimation(self.L3_12))
        self.gridLayout_7.addWidget(self.L3_12, 1, 0, 1, 1)
        self.L3_13 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_13.setObjectName("L3_13")
        self.L3_13.clicked.connect(lambda: self.startAnimation(self.L3_13))
        self.gridLayout_7.addWidget(self.L3_13, 1, 1, 1, 1)
        self.L3_14 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_14.setObjectName("L3_14")
        self.L3_14.clicked.connect(lambda: self.startAnimation(self.L3_14))
        self.gridLayout_7.addWidget(self.L3_14, 1, 2, 1, 1)
        self.L3_15 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_15.setObjectName("L3_15")
        self.L3_15.clicked.connect(lambda: self.startAnimation(self.L3_15))
        self.gridLayout_7.addWidget(self.L3_15, 1, 3, 1, 1)
        self.L3_8 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_8.setObjectName("L3_8")
        self.L3_8.clicked.connect(lambda: self.startAnimation(self.L3_8))
        self.gridLayout_7.addWidget(self.L3_8, 2, 0, 1, 1)
        self.L3_9 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_9.setObjectName("L3_9")
        self.L3_9.clicked.connect(lambda: self.startAnimation(self.L3_9))
        self.gridLayout_7.addWidget(self.L3_9, 2, 1, 1, 1)
        self.L3_10 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_10.setObjectName("L3_10")
        self.L3_10.clicked.connect(lambda: self.startAnimation(self.L3_10))
        self.gridLayout_7.addWidget(self.L3_10, 2, 2, 1, 1)
        self.L3_11 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_11.setObjectName("L3_11")
        self.L3_11.clicked.connect(lambda: self.startAnimation(self.L3_11))
        self.gridLayout_7.addWidget(self.L3_11, 2, 3, 1, 1)
        self.L3_4 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_4.setObjectName("L3_4")
        self.L3_4.clicked.connect(lambda: self.startAnimation(self.L3_4))
        self.gridLayout_7.addWidget(self.L3_4, 3, 0, 1, 1)
        self.L3_5 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_5.setObjectName("L3_5")
        self.L3_5.clicked.connect(lambda: self.startAnimation(self.L3_5))
        self.gridLayout_7.addWidget(self.L3_5, 3, 1, 1, 1)
        self.L3_6 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_6.setObjectName("L3_6")
        self.L3_6.clicked.connect(lambda: self.startAnimation(self.L3_6))
        self.gridLayout_7.addWidget(self.L3_6, 3, 2, 1, 1)
        self.L3_7 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_7.setObjectName("L3_7")
        self.L3_7.clicked.connect(lambda: self.startAnimation(self.L3_7))
        self.gridLayout_7.addWidget(self.L3_7, 3, 3, 1, 1)
        self.L3_G = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_G.setObjectName("L3_0")
        self.L3_G.clicked.connect(lambda: self.startAnimation(self.L3_G))
        self.gridLayout_7.addWidget(self.L3_G, 4, 0, 1, 1)
        self.L3_1 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_1.setObjectName("L3_1")
        self.L3_1.clicked.connect(lambda: self.startAnimation(self.L3_1))
        self.gridLayout_7.addWidget(self.L3_1, 4, 1, 1, 1)
        self.L3_2 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_2.setObjectName("L3_2")
        self.L3_2.clicked.connect(lambda: self.startAnimation(self.L3_2))
        self.gridLayout_7.addWidget(self.L3_2, 4, 2, 1, 1)
        self.L3_3 = QtWidgets.QPushButton(self.L3_Dest)
        self.L3_3.setObjectName("L3_3")
        self.L3_3.clicked.connect(lambda: self.startAnimation(self.L3_3))
        self.gridLayout_7.addWidget(self.L3_3, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_9, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.widget1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Queue1 = QtWidgets.QTextEdit(self.frame_4)
        self.Queue1.setGeometry(QtCore.QRect(10, 42, 231, 91))
        self.Queue1.setObjectName("Queue1")
        self.Queue1.setReadOnly(1)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(16, 2, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.L1_Dest = QtWidgets.QFrame(self.frame_4)
        self.L1_Dest.setGeometry(QtCore.QRect(0, 140, 251, 211))
        self.L1_Dest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.L1_Dest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.L1_Dest.setObjectName("L1_Dest")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.L1_Dest)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.L1_16 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_16.setObjectName("L1_16")
        self.L1_16.clicked.connect(lambda: self.startAnimation(self.L1_16))
        self.gridLayout_5.addWidget(self.L1_16, 0, 0, 1, 1)
        self.L1_17 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_17.setObjectName("L1_17")
        self.L1_17.clicked.connect(lambda: self.startAnimation(self.L1_17))
        self.gridLayout_5.addWidget(self.L1_17, 0, 1, 1, 1)
        self.L1_18 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_18.setObjectName("L1_18")
        self.L1_18.clicked.connect(lambda: self.startAnimation(self.L1_18))
        self.gridLayout_5.addWidget(self.L1_18, 0, 2, 1, 1)
        self.L1_19 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_19.setObjectName("L1_19")
        self.L1_19.clicked.connect(lambda: self.startAnimation(self.L1_19))
        self.gridLayout_5.addWidget(self.L1_19, 0, 3, 1, 1)
        self.L1_12 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_12.setObjectName("L1_12")
        self.L1_12.clicked.connect(lambda: self.startAnimation(self.L1_12))
        self.gridLayout_5.addWidget(self.L1_12, 1, 0, 1, 1)
        self.L1_13 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_13.setObjectName("L1_13")
        self.L1_13.clicked.connect(lambda: self.startAnimation(self.L1_13))
        self.gridLayout_5.addWidget(self.L1_13, 1, 1, 1, 1)
        self.L1_14 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_14.setObjectName("L1_14")
        self.L1_14.clicked.connect(lambda: self.startAnimation(self.L1_14))
        self.gridLayout_5.addWidget(self.L1_14, 1, 2, 1, 1)
        self.L1_15 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_15.setObjectName("L1_15")
        self.L1_15.clicked.connect(lambda: self.startAnimation(self.L1_15))
        self.gridLayout_5.addWidget(self.L1_15, 1, 3, 1, 1)
        self.L1_8 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_8.setObjectName("L1_8")
        self.L1_8.clicked.connect(lambda: self.startAnimation(self.L1_8))
        self.gridLayout_5.addWidget(self.L1_8, 2, 0, 1, 1)
        self.L1_9 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_9.setObjectName("L1_9")
        self.L1_9.clicked.connect(lambda: self.startAnimation(self.L1_9))
        self.gridLayout_5.addWidget(self.L1_9, 2, 1, 1, 1)
        self.L1_10 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_10.setObjectName("L1_10")
        self.L1_10.clicked.connect(lambda: self.startAnimation(self.L1_10))
        self.gridLayout_5.addWidget(self.L1_10, 2, 2, 1, 1)
        self.L1_11 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_11.setObjectName("L1_11")
        self.L1_11.clicked.connect(lambda: self.startAnimation(self.L1_11))
        self.gridLayout_5.addWidget(self.L1_11, 2, 3, 1, 1)
        self.L1_4 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_4.setObjectName("L1_4")
        self.L1_4.clicked.connect(lambda: self.startAnimation(self.L1_4))
        self.gridLayout_5.addWidget(self.L1_4, 3, 0, 1, 1)
        self.L1_5 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_5.setObjectName("L1_5")
        self.L1_5.clicked.connect(lambda: self.startAnimation(self.L1_5))
        self.gridLayout_5.addWidget(self.L1_5, 3, 1, 1, 1)
        self.L1_6 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_6.setObjectName("L1_6")
        self.L1_6.clicked.connect(lambda: self.startAnimation(self.L1_6))
        self.gridLayout_5.addWidget(self.L1_6, 3, 2, 1, 1)
        self.L1_7 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_7.setObjectName("L1_7")
        self.L1_7.clicked.connect(lambda: self.startAnimation(self.L1_7))
        self.gridLayout_5.addWidget(self.L1_7, 3, 3, 1, 1)
        self.L1_G = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_G.setObjectName("L1_0")
        self.L1_G.clicked.connect(lambda: self.startAnimation(self.L1_G))
        self.gridLayout_5.addWidget(self.L1_G, 4, 0, 1, 1)
        self.L1_1 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_1.setObjectName("L1_1")
        self.L1_1.clicked.connect(lambda: self.startAnimation(self.L1_1))
        self.gridLayout_5.addWidget(self.L1_1, 4, 1, 1, 1)
        self.L1_2 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_2.setObjectName("L1_2")
        self.L1_2.clicked.connect(lambda: self.startAnimation(self.L1_2))
        self.gridLayout_5.addWidget(self.L1_2, 4, 2, 1, 1)
        self.L1_3 = QtWidgets.QPushButton(self.L1_Dest)
        self.L1_3.setObjectName("L1_3")
        self.L1_3.clicked.connect(lambda: self.startAnimation(self.L1_3))
        self.gridLayout_5.addWidget(self.L1_3, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.widget1)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.Queue4 = QtWidgets.QTextEdit(self.frame_11)
        self.Queue4.setGeometry(QtCore.QRect(10, 42, 231, 91))
        self.Queue4.setObjectName("Queue4")
        self.Queue4.setReadOnly(1)
        self.label_29 = QtWidgets.QLabel(self.frame_11)
        self.label_29.setGeometry(QtCore.QRect(16, 2, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.L4_Dest = QtWidgets.QFrame(self.frame_11)
        self.L4_Dest.setGeometry(QtCore.QRect(0, 140, 251, 211))
        self.L4_Dest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.L4_Dest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.L4_Dest.setObjectName("L4_Dest")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.L4_Dest)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.L4_16 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_16.setObjectName("L4_16")
        self.L4_16.clicked.connect(lambda: self.startAnimation(self.L4_16))
        self.gridLayout_8.addWidget(self.L4_16, 0, 0, 1, 1)
        self.L4_17 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_17.setObjectName("L4_17")
        self.L4_17.clicked.connect(lambda: self.startAnimation(self.L4_17))
        self.gridLayout_8.addWidget(self.L4_17, 0, 1, 1, 1)
        self.L4_18 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_18.setObjectName("L4_18")
        self.L4_18.clicked.connect(lambda: self.startAnimation(self.L4_18))
        self.gridLayout_8.addWidget(self.L4_18, 0, 2, 1, 1)
        self.L4_19 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_19.setObjectName("L4_19")
        self.L4_19.clicked.connect(lambda: self.startAnimation(self.L4_19))
        self.gridLayout_8.addWidget(self.L4_19, 0, 3, 1, 1)
        self.L4_12 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_12.setObjectName("L4_12")
        self.L4_12.clicked.connect(lambda: self.startAnimation(self.L4_12))
        self.gridLayout_8.addWidget(self.L4_12, 1, 0, 1, 1)
        self.L4_13 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_13.setObjectName("L4_13")
        self.L4_13.clicked.connect(lambda: self.startAnimation(self.L4_13))
        self.gridLayout_8.addWidget(self.L4_13, 1, 1, 1, 1)
        self.L4_14 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_14.setObjectName("L4_14")
        self.L4_14.clicked.connect(lambda: self.startAnimation(self.L4_14))
        self.gridLayout_8.addWidget(self.L4_14, 1, 2, 1, 1)
        self.L4_15 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_15.setObjectName("L4_15")
        self.L4_15.clicked.connect(lambda: self.startAnimation(self.L4_15))
        self.gridLayout_8.addWidget(self.L4_15, 1, 3, 1, 1)
        self.L4_8 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_8.setObjectName("L4_8")
        self.L4_8.clicked.connect(lambda: self.startAnimation(self.L4_8))
        self.gridLayout_8.addWidget(self.L4_8, 2, 0, 1, 1)
        self.L4_9 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_9.setObjectName("L4_9")
        self.L4_9.clicked.connect(lambda: self.startAnimation(self.L4_9))
        self.gridLayout_8.addWidget(self.L4_9, 2, 1, 1, 1)
        self.L4_10 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_10.setObjectName("L4_10")
        self.L4_10.clicked.connect(lambda: self.startAnimation(self.L4_10))
        self.gridLayout_8.addWidget(self.L4_10, 2, 2, 1, 1)
        self.L4_11 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_11.setObjectName("L4_11")
        self.L4_11.clicked.connect(lambda: self.startAnimation(self.L4_11))
        self.gridLayout_8.addWidget(self.L4_11, 2, 3, 1, 1)
        self.L4_4 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_4.setObjectName("L4_4")
        self.L4_4.clicked.connect(lambda: self.startAnimation(self.L4_4))
        self.gridLayout_8.addWidget(self.L4_4, 3, 0, 1, 1)
        self.L4_5 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_5.setObjectName("L4_5")
        self.L4_5.clicked.connect(lambda: self.startAnimation(self.L4_5))
        self.gridLayout_8.addWidget(self.L4_5, 3, 1, 1, 1)
        self.L4_6 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_6.setObjectName("L4_6")
        self.L4_6.clicked.connect(lambda: self.startAnimation(self.L4_6))
        self.gridLayout_8.addWidget(self.L4_6, 3, 2, 1, 1)
        self.L4_7 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_7.setObjectName("L4_7")
        self.L4_7.clicked.connect(lambda: self.startAnimation(self.L4_7))
        self.gridLayout_8.addWidget(self.L4_7, 3, 3, 1, 1)
        self.L4_G = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_G.setObjectName("L4_0")
        self.L4_G.clicked.connect(lambda: self.startAnimation(self.L4_G))
        self.gridLayout_8.addWidget(self.L4_G, 4, 0, 1, 1)
        self.L4_1 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_1.setObjectName("L4_1")
        self.L4_1.clicked.connect(lambda: self.startAnimation(self.L4_1))
        self.gridLayout_8.addWidget(self.L4_1, 4, 1, 1, 1)
        self.L4_2 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_2.setObjectName("L4_2")
        self.L4_2.clicked.connect(lambda: self.startAnimation(self.L4_2))
        self.gridLayout_8.addWidget(self.L4_2, 4, 2, 1, 1)
        self.L4_3 = QtWidgets.QPushButton(self.L4_Dest)
        self.L4_3.setObjectName("L4_3")
        self.L4_3.clicked.connect(lambda: self.startAnimation(self.L4_3))
        self.gridLayout_8.addWidget(self.L4_3, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_11, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.widget1)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.Queue2 = QtWidgets.QTextEdit(self.frame_7)
        self.Queue2.setGeometry(QtCore.QRect(10, 42, 231, 91))
        self.Queue2.setObjectName("Queue2")
        self.Queue2.setReadOnly(1)
        self.msgBox1 = QtWidgets.QMessageBox()
        self.msgBox1.setIcon(QtWidgets.QMessageBox.Information)
        self.msgBox2 = QtWidgets.QMessageBox()
        self.msgBox2.setIcon(QtWidgets.QMessageBox.Information)
        self.msgBox3 = QtWidgets.QMessageBox()
        self.msgBox3.setIcon(QtWidgets.QMessageBox.Information)
        self.Refresh = QtWidgets.QPushButton(self.frame_7)
        self.Refresh.setGeometry(QtCore.QRect(73, 2, 41, 31))
        self.Refresh.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/ref.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh.setIcon(icon5)
        self.Refresh.setIconSize(QtCore.QSize(36, 26))
        self.Refresh.setObjectName("Refresh")
        self.Refresh.clicked.connect(self.back_to_normal)
        self.Emergency_Button = QtWidgets.QPushButton(self.frame_7)
        self.Emergency_Button.setGeometry(QtCore.QRect(214, 2, 41, 31))
        self.Emergency_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/fire.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Emergency_Button.setIcon(icon2)
        self.Emergency_Button.setIconSize(QtCore.QSize(35, 24))
        self.Emergency_Button.setObjectName("Emergency_Button")
        self.Emergency_Button.clicked.connect(lambda :self.TextBox(1))
        self.Emergency_Button_2 = QtWidgets.QPushButton(self.frame_7)
        self.Emergency_Button_2.setGeometry(QtCore.QRect(166, 2, 41, 31))
        self.Emergency_Button_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/flood.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Emergency_Button_2.setIcon(icon3)
        self.Emergency_Button_2.setIconSize(QtCore.QSize(36, 26))
        self.Emergency_Button_2.setObjectName("Emergency_Button_2")
        self.Emergency_Button_2.clicked.connect(lambda: self.TextBox(2))
        self.Emergency_Button_3 = QtWidgets.QPushButton(self.frame_7)
        self.Emergency_Button_3.setGeometry(QtCore.QRect(120, 2, 41, 31))
        self.Emergency_Button_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/threat.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Emergency_Button_3.setIcon(icon4)
        self.Emergency_Button_3.setIconSize(QtCore.QSize(36, 36))
        self.Emergency_Button_3.setObjectName("Emergency_Button_3")
        self.Emergency_Button_3.clicked.connect(lambda: self.TextBox(3))
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setGeometry(QtCore.QRect(10, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.L2_Dest = QtWidgets.QFrame(self.frame_7)
        self.L2_Dest.setGeometry(QtCore.QRect(0, 140, 251, 211))
        self.L2_Dest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.L2_Dest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.L2_Dest.setObjectName("L2_Dest")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.L2_Dest)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.L2_16 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_16.setObjectName("L2_16")
        self.L2_16.clicked.connect(lambda: self.startAnimation(self.L2_16))
        self.gridLayout_6.addWidget(self.L2_16, 0, 0, 1, 1)
        self.L2_17 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_17.setObjectName("L2_17")
        self.L2_17.clicked.connect(lambda: self.startAnimation(self.L2_17))
        self.gridLayout_6.addWidget(self.L2_17, 0, 1, 1, 1)
        self.L2_18 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_18.setObjectName("L2_18")
        self.L2_18.clicked.connect(lambda: self.startAnimation(self.L2_18))
        self.gridLayout_6.addWidget(self.L2_18, 0, 2, 1, 1)
        self.L2_19 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_19.setObjectName("L2_19")
        self.L2_19.clicked.connect(lambda: self.startAnimation(self.L2_19))
        self.gridLayout_6.addWidget(self.L2_19, 0, 3, 1, 1)
        self.L2_12 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_12.setObjectName("L2_12")
        self.L2_12.clicked.connect(lambda: self.startAnimation(self.L2_12))
        self.gridLayout_6.addWidget(self.L2_12, 1, 0, 1, 1)
        self.L2_13 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_13.setObjectName("L2_13")
        self.L2_13.clicked.connect(lambda: self.startAnimation(self.L2_13))
        self.gridLayout_6.addWidget(self.L2_13, 1, 1, 1, 1)
        self.L2_14 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_14.setObjectName("L2_14")
        self.L2_14.clicked.connect(lambda: self.startAnimation(self.L2_14))
        self.gridLayout_6.addWidget(self.L2_14, 1, 2, 1, 1)
        self.L2_15 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_15.setObjectName("L2_15")
        self.L2_15.clicked.connect(lambda: self.startAnimation(self.L2_15))
        self.gridLayout_6.addWidget(self.L2_15, 1, 3, 1, 1)
        self.L2_8 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_8.setObjectName("L2_8")
        self.L2_8.clicked.connect(lambda: self.startAnimation(self.L2_8))
        self.gridLayout_6.addWidget(self.L2_8, 2, 0, 1, 1)
        self.L2_9 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_9.setObjectName("L2_9")
        self.L2_9.clicked.connect(lambda: self.startAnimation(self.L2_9))
        self.gridLayout_6.addWidget(self.L2_9, 2, 1, 1, 1)
        self.L2_10 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_10.setObjectName("L2_10")
        self.L2_10.clicked.connect(lambda: self.startAnimation(self.L2_10))
        self.gridLayout_6.addWidget(self.L2_10, 2, 2, 1, 1)
        self.L2_11 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_11.setObjectName("L2_11")
        self.L2_11.clicked.connect(lambda: self.startAnimation(self.L2_11))
        self.gridLayout_6.addWidget(self.L2_11, 2, 3, 1, 1)
        self.L2_4 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_4.setObjectName("L2_4")
        self.L2_4.clicked.connect(lambda: self.startAnimation(self.L2_4))
        self.gridLayout_6.addWidget(self.L2_4, 3, 0, 1, 1)
        self.L2_5 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_5.setObjectName("L2_5")
        self.L2_5.clicked.connect(lambda: self.startAnimation(self.L2_5))
        self.gridLayout_6.addWidget(self.L2_5, 3, 1, 1, 1)
        self.L2_6 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_6.setObjectName("L2_6")
        self.L2_6.clicked.connect(lambda: self.startAnimation(self.L2_6))
        self.gridLayout_6.addWidget(self.L2_6, 3, 2, 1, 1)
        self.L2_7 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_7.setObjectName("L2_7")
        self.L2_7.clicked.connect(lambda: self.startAnimation(self.L2_7))
        self.gridLayout_6.addWidget(self.L2_7, 3, 3, 1, 1)
        self.L2_G = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_G.setObjectName("L2_0")
        self.L2_G.clicked.connect(lambda: self.startAnimation(self.L2_G))
        self.gridLayout_6.addWidget(self.L2_G, 4, 0, 1, 1)
        self.L2_1 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_1.setObjectName("L2_1")
        self.L2_1.clicked.connect(lambda: self.startAnimation(self.L2_1))
        self.gridLayout_6.addWidget(self.L2_1, 4, 1, 1, 1)
        self.L2_2 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_2.setObjectName("L2_2")
        self.L2_2.clicked.connect(lambda: self.startAnimation(self.L2_2))
        self.gridLayout_6.addWidget(self.L2_2, 4, 2, 1, 1)
        self.L2_3 = QtWidgets.QPushButton(self.L2_Dest)
        self.L2_3.setObjectName("L2_3")
        self.L2_3.clicked.connect(lambda: self.startAnimation(self.L2_3))
        self.gridLayout_6.addWidget(self.L2_3, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_7, 0, 1, 1, 1)

        self.anim1 = QPropertyAnimation(self.Car1, b"geometry")
        self.anim2 = QPropertyAnimation(self.Car2, b"geometry")
        self.anim3 = QPropertyAnimation(self.Car3, b"geometry")
        self.anim4 = QPropertyAnimation(self.Car4, b"geometry")
        self.anim5 = QPropertyAnimation(self.Car1, b"geometry")
        self.anim6 = QPropertyAnimation(self.Car2, b"geometry")
        self.anim7 = QPropertyAnimation(self.Car3, b"geometry")
        self.anim8 = QPropertyAnimation(self.Car4, b"geometry")
        self.timer1 = QTimer()
        self.timer2 = QTimer()
        self.timer3 = QTimer()
        self.timer4 = QTimer()
        self.timer5 = QTimer()
        self.timer6 = QTimer()
        self.timer7 = QTimer()
        self.timer8 = QTimer()
        self.timer9 = QTimer()
        self.timer10 = QTimer()
        self.timer11 = QTimer()
        self.timer12 = QTimer()
        self.timer13 = QTimer()
        self.timer14 = QTimer()
        self.timer15 = QTimer()
        self.timer16 = QTimer()
        self.group = QParallelAnimationGroup()

        self.retranslateUi(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_28.setText(_translate("Form", "Lift 3"))
        self.L3_16.setText(_translate("Form", "16"))
        self.L3_17.setText(_translate("Form", "17"))
        self.L3_18.setText(_translate("Form", "18"))
        self.L3_19.setText(_translate("Form", "19"))
        self.L3_12.setText(_translate("Form", "12"))
        self.L3_13.setText(_translate("Form", "13"))
        self.L3_14.setText(_translate("Form", "14"))
        self.L3_15.setText(_translate("Form", "15"))
        self.L3_8.setText(_translate("Form", "8"))
        self.L3_9.setText(_translate("Form", "9"))
        self.L3_10.setText(_translate("Form", "10"))
        self.L3_11.setText(_translate("Form", "11"))
        self.L3_4.setText(_translate("Form", "4"))
        self.L3_5.setText(_translate("Form", "5"))
        self.L3_6.setText(_translate("Form", "6"))
        self.L3_7.setText(_translate("Form", "7"))
        self.L3_G.setText(_translate("Form", "G"))
        self.L3_1.setText(_translate("Form", "1"))
        self.L3_2.setText(_translate("Form", "2"))
        self.L3_3.setText(_translate("Form", "3"))
        self.label_26.setText(_translate("Form", "Lift 1"))
        self.L1_16.setText(_translate("Form", "16"))
        self.L1_17.setText(_translate("Form", "17"))
        self.L1_18.setText(_translate("Form", "18"))
        self.L1_19.setText(_translate("Form", "19"))
        self.L1_12.setText(_translate("Form", "12"))
        self.L1_13.setText(_translate("Form", "13"))
        self.L1_14.setText(_translate("Form", "14"))
        self.L1_15.setText(_translate("Form", "15"))
        self.L1_8.setText(_translate("Form", "8"))
        self.L1_9.setText(_translate("Form", "9"))
        self.L1_10.setText(_translate("Form", "10"))
        self.L1_11.setText(_translate("Form", "11"))
        self.L1_4.setText(_translate("Form", "4"))
        self.L1_5.setText(_translate("Form", "5"))
        self.L1_6.setText(_translate("Form", "6"))
        self.L1_7.setText(_translate("Form", "7"))
        self.L1_G.setText(_translate("Form", "G"))
        self.L1_1.setText(_translate("Form", "1"))
        self.L1_2.setText(_translate("Form", "2"))
        self.L1_3.setText(_translate("Form", "3"))
        self.label_29.setText(_translate("Form", "Lift 4"))
        self.L4_16.setText(_translate("Form", "16"))
        self.L4_17.setText(_translate("Form", "17"))
        self.L4_18.setText(_translate("Form", "18"))
        self.L4_19.setText(_translate("Form", "19"))
        self.L4_12.setText(_translate("Form", "12"))
        self.L4_13.setText(_translate("Form", "13"))
        self.L4_14.setText(_translate("Form", "14"))
        self.L4_15.setText(_translate("Form", "15"))
        self.L4_8.setText(_translate("Form", "8"))
        self.L4_9.setText(_translate("Form", "9"))
        self.L4_10.setText(_translate("Form", "10"))
        self.L4_11.setText(_translate("Form", "11"))
        self.L4_4.setText(_translate("Form", "4"))
        self.L4_5.setText(_translate("Form", "5"))
        self.L4_6.setText(_translate("Form", "6"))
        self.L4_7.setText(_translate("Form", "7"))
        self.L4_G.setText(_translate("Form", "G"))
        self.L4_1.setText(_translate("Form", "1"))
        self.L4_2.setText(_translate("Form", "2"))
        self.L4_3.setText(_translate("Form", "3"))
        self.label_27.setText(_translate("Form", "Lift 2"))
        self.L2_16.setText(_translate("Form", "16"))
        self.L2_17.setText(_translate("Form", "17"))
        self.L2_18.setText(_translate("Form", "18"))
        self.L2_19.setText(_translate("Form", "19"))
        self.L2_12.setText(_translate("Form", "12"))
        self.L2_13.setText(_translate("Form", "13"))
        self.L2_14.setText(_translate("Form", "14"))
        self.L2_15.setText(_translate("Form", "15"))
        self.L2_8.setText(_translate("Form", "8"))
        self.L2_9.setText(_translate("Form", "9"))
        self.L2_10.setText(_translate("Form", "10"))
        self.L2_11.setText(_translate("Form", "11"))
        self.L2_4.setText(_translate("Form", "4"))
        self.L2_5.setText(_translate("Form", "5"))
        self.L2_6.setText(_translate("Form", "6"))
        self.L2_7.setText(_translate("Form", "7"))
        self.L2_G.setText(_translate("Form", "G"))
        self.L2_1.setText(_translate("Form", "1"))
        self.L2_2.setText(_translate("Form", "2"))
        self.L2_3.setText(_translate("Form", "3"))
        self.label_21.setText(_translate("Form", "19"))
        self.label_22.setText(_translate("Form", "18"))
        self.label_23.setText(_translate("Form", "17"))
        self.label_24.setText(_translate("Form", "16"))
        self.label_25.setText(_translate("Form", "15"))
        self.label_226.setText(_translate("Form", "14"))
        self.label_227.setText(_translate("Form", "13"))
        self.label_228.setText(_translate("Form", "12"))
        self.label_229.setText(_translate("Form", "11"))
        self.label_30.setText(_translate("Form", "10"))
        self.label_31.setText(_translate("Form", "9"))
        self.label_32.setText(_translate("Form", "8"))
        self.label_33.setText(_translate("Form", "7"))
        self.label_34.setText(_translate("Form", "6"))
        self.label_35.setText(_translate("Form", "5"))
        self.label_36.setText(_translate("Form", "4"))
        self.label_37.setText(_translate("Form", "3"))
        self.label_38.setText(_translate("Form", "2"))
        self.label_39.setText(_translate("Form", "1"))
        self.label_40.setText(_translate("Form", "G"))
